name: deliverFood
description: app de entrega de pedidos de productos.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  http: ^0.12.2
  toast: ^0.1.5
  loading: ^1.0.2
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/categorias/

  # fonts:
  #   family: FiraCode
  #   fonts:
  #     - asset: fonts/FiraCode-Regular.ttf
  #     - asset: fonts/FiraCode-Bold.ttf
  #       style: bold
  #     - asset: fonts/FiraCode-SemiBold.ttf
  #       style: semiBold
  #     - asset: assets/fonts/FiraCode-Retina.ttf
  #       style: retina
  #     - asset: assets/fonts/FiraCode-Medium.ttf
  #       style: meduim
  #     - asset: assets/fonts/FiraCode-Light.ttf
  #       style: light

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
